### ISSUE TITLE
Examples of how it works and looks like

### ISSUE THREAD

**Issue by timagixe** [Teamial/DevTrack#4]
would be nice to add some examples to readme to the real projects of people to see how does it look like, before setting it up for myself

**Comment by Teamial** [comment]
Hi I just updated the readme to include my personal example of how it looks and works, check it out and let me know if it looks good.

**Comment by timagixe** [comment]
Hi @Teamial , the link in readme is broken - https://github.com/username/code-tracking

I have tried to change username to yours - but it is still broken - https://github.com/Teamial/code-tracking

**Comment by timagixe** [comment]
Maybe your repository is private?

**Comment by Teamial** [comment]
Yeah my code-tracking repository is private but I’ll make it public so you
can see it
